name: Deploy Anchore Task Version

on:
  push:
    branches: master

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Restore Dependencies
      working-directory: anchoreScanTask
      run: npm install
        
    - name: Build Distribution
      working-directory: anchoreScanTask
      run: tsc
      
    - name: Create Output Directory
      run: |
        mkdir -p deploy/anchoreScanTask
      
    - name: Copy Artifacts
      run: |
        cp -r ./anchoreScanTask/dist deploy/dist
        cp -r ./anchoreScanTask/node_modules deploy/node_modules
        cp -r ./images deploy/images
        cp ./anchoreScanTask/icon.png deploy/anchoreScanTask/
        cp ./anchoreScanTask/task.json deploy/anchoreScanTask/
        cp ./vss-extension.json deploy/
          
    - name: (debug) List all contents
      run: |
        ls -l deploy
        ls -l deploy/anchoreScanTask
      
