name: Deploy Anchore Task Version

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Restore Node modules
      run: |
        cd buildAndReleaseTask
        npm install

    - name: Compile Typescript
      run: tsc

    - name: Prepare Deployment Directory
      run: |
        mkdir deployment
        mv buildAndReleaseTask/dist deployment/buildAndReleaseTask
        cp buildAndReleaseTask/task.json deployment/buildAndReleaseTask
        cp vss-extension.json deployment

    - name: Validate Structure (debug)
      run: |
        ls -la
        ls -la deployment
        ls -la deployment/buildAndReleaseTask
