name: Deploy Anchore Task Version

on:
  push:
    tags: v*

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Restore Node modules
      run: |
        cd buildAndReleaseTask
        npm install

    - name: Compile Typescript
      run: tsc --build buildAndReleaseTask/tsconfig.json

  prepare:
    - name: Prepare Deployment Directory
      run: |
        mkdir deployment
        mv buildAndReleaseTask/dist deployment/buildAndReleaseTask
        cp buildAndReleaseTask/task.json deployment/buildAndReleaseTask
        cp vss-extension.json deployment

    - name: Update Extension Version
      run: |
        cd deployment

  #deploy:
    #- name: Create VSIX
    #  run: |
    #    npm install -g tfx-cli
    #    cd deployment
    #    tfx extension create --manifest-globs vss-extension.json
    #
    #- name: Upload VSIX Artifact
