name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Compile Typescript
      run: tsc
    - name: Install jq
      run: apt-get install jq
