name: Deploy Anchore Task Version

on:
  push:
    branches: master

jobs:
  publish:
    name: Publish Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Restore Dependencies
      working-directory: anchoreScanTask
      run: npm install
        
    - name: Build Distribution
      working-directory: anchoreScanTask
      run: tsc
      
    - name: Prepare for Publishing
      run: |
        mkdir -p deploy/anchoreScanTask
        sudo npm install -g tfx-cli
      
    - name: Copy Files for Artifact
      run: |
        cp -r anchoreScanTask/dist deploy/anchoreScanTask/
        cp -r anchoreScanTask/node_modules deploy/anchoreScanTask/
        cp -r ./images deploy/images
        cp ./anchoreScanTask/icon.png deploy/anchoreScanTask/
        cp ./anchoreScanTask/task.json deploy/anchoreScanTask/
        cp ./vss-extension.json deploy/
          
    - name: Create Artifact
      run: tfx extension create --manifest-globs vss-extension.json
      working-directory: deploy/
    
    - name: List directory contents (debug)
      run: ls -l
      working-directory: deploy/
      
