name: Deploy Anchore Task Version

on:
  push:
    tags: v*

jobs:
  publish:
    name: Publish Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Restore Dependencies
      working-directory: anchoreScanTask
      run: npm install
        
    - name: Build Distribution
      working-directory: anchoreScanTask
      run: tsc
      
    - name: Prepare for Publishing
      run: |
        mkdir -p deploy/anchoreScanTask
        sudo npm install -g tfx-cli
      
    - name: Copy Files for Artifact
      run: |
        cp -r anchoreScanTask/dist deploy/anchoreScanTask/
        cp -r anchoreScanTask/node_modules deploy/anchoreScanTask/
        cp -r ./images deploy
        cp ./anchoreScanTask/icon.png deploy/anchoreScanTask/
        cp ./anchoreScanTask/task.json deploy/anchoreScanTask/
        cp ./vss-extension.json deploy/
        cp ./README.md deploy/
        cp ./eula.md deploy/
    
    - name: Version Artifact
      run: node scripts/version_glob.js $GITHUB_REF deploy/vss-extension.json
      
    - name: Publish Artifact
      run: tfx extension publish --manifest-globs vss-extension.json -t ${{ secrets.MARKETPLACE_TOKEN }}
      working-directory: deploy/
      
