name: Deploy Anchore Task Version

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Compile Typescript
      run: tsc --outDir deployment
    - name: Update Extension Version
      run: ls -la
