name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/typescript-action@v1
    - name: Compile Typescript
      run: tsc
