# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ task/* ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Publish Package

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      working-directory: anchoreScanTask
      run: |
        npm install
        sudo npm install -g tfx-cli

    - name: Build Task
      working-directory: anchoreScanTask
      run: tsc

    - name: Get Current Version
      working-directory: anchoreScanTask
      run: |
        current_version=$(tfx extension show -t ${{ secrets.MarketplaceToken }} --publisher Farrellsoft --extension-id anchore-task --output json | jq '.versions | .[0].version')
        echo $current_version
