# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ task/* ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Publish Package

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      working-directory: anchoreScanTask
      run: |
        npm install
        sudo npm install -g tfx-cli semver

    - name: Prepare Task
      working-directory: anchoreScanTask
      run: |
        tsc
        mv task.dev.json task.json

    - name: Rev Manifest
      run: |
        current_version=$(tfx extension show -t ${{ secrets.MarketplaceToken }} --publisher Farrellsoft --extension-id anchore-task --output json | jq '.versions | .[0].version')
        current_version=$(echo $current_version | sed -e 's/^"//' -e 's/"$//')
        new_version=$(semver -i $current_version)
        json=$(cat vss-extension.dev.json | jq --arg v "${new_version}" '.version = $v')
        echo $json > vss-extension.dev.json

    - name: Publish Extension
      run: |
        tfx extension publish -t ${{ secrets.MarketplaceToken }} --share-with Farrellsoft --manifests vss-extension.dev.json
        echo "Done"
