name: Release

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Package

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: anchoreScanTask
        run: |
          npm install
          sudo npm install -g tfx-cli semver

      - name: Prepare Task
        working-directory: anchoreScanTask
        run: |
          tsc
          mv task.release.json task.json

      - name: Rev Manifest
        run: |
          echo ${GITHUB_REF##*/}